import type { components } from './generated/api-schema'

export type SnapshotMeta = components['schemas']['SnapshotMeta']
export type Overview = components['schemas']['Overview']
export type StudyList = components['schemas']['StudyList']
export type ExperimentSummary = components['schemas']['ExperimentSummary']
export type ExperimentDetail = components['schemas']['ExperimentDetail']
export type ExperimentPage = components['schemas']['ExperimentPage']
export type Metric = components['schemas']['Metric']
export type SeriesMeta = components['schemas']['SeriesMeta']
export type SeriesResponse = components['schemas']['SeriesResponse']
export type CompatibilityResult = components['schemas']['CompatibilityResult']
export type SignalsSummary = components['schemas']['SignalsSummary']
export type ProspectiveSummary = components['schemas']['ProspectiveSummary']
export type ProspectiveDay = components['schemas']['ProspectiveDay']
export type HealthSummary = components['schemas']['HealthSummary']
export type RuntimeStatus = components['schemas']['RuntimeStatus']
export type EvidenceSummary = components['schemas']['EvidenceSummary']
export type ReloadResult = components['schemas']['ReloadResult']
export type ExportRequest = components['schemas']['ExportRequest']
